apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-deep-lemming
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "130405883059"
    provider: eks
    region: us-west-1
    registry: 130405883059.dkr.ecr.us-west-1.amazonaws.com
  environments:
  - key: dev
    owner: lexarflash8g
    repository: jx3-eks-vault
  - key: staging
  - key: production
  ingress:
    domain: 52.53.71.84.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: lexarflash8g
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-tf-jx-deep-lemming-20210313042444944300000009
  - name: reports
    url: s3://reports-tf-jx-deep-lemming-20210313042443810600000002
  - name: repository
    url: s3://repository-tf-jx-deep-lemming-20210313042443813200000005
  terraform: true
  vault:
    aws:
      dynamoDBRegion: us-west-1
      dynamoDBTable: vault-unseal-tf-jx-deep-lemming-Rc2Zx8kB
      kmsKeyId: 4f2c441c-d311-497d-9901-0071080cd238
      kmsRegion: us-west-1
      s3Bucket: vault-unseal-tf-jx-deep-lemming-20210313042443810800000003
      s3Region: us-west-1
  webhook: lighthouse
